### GET request to example server
GET localhost:8080/api/test/success
Content-Type: application/json

### GET request to example server
GET localhost:8080/api/test/failure
Content-Type: application/json